# Generated by Django 4.1 on 2022-11-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255)),
                ('first_name', models.CharField(default='Анон', max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('growth', models.IntegerField()),
                ('base_metabolism', models.IntegerField()),
            ],
        ),
    ]
