# Generated by Django 4.1 on 2022-11-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_sex_alter_users_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.IntegerField(default=0),
        ),
    ]
